# Runs a complete build for the api
---
name: Api CI
on:
  pull_request:
    branches: [develop, main]

concurrency:
  group: ${{ github.head_ref }}-ci
  cancel-in-progress: true

env:
  working-dir: ./api

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew
        working-directory: ${{ env.working-dir }}

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean build
          build-root-directory: ${{ env.working-dir }}
